### ISSUE TITLE
CAD pricing display

### ISSUE THREAD

**Issue by shaneaustin** [voceconnect/eventbrite-venue#5]
The pricing display meta for each event doesn't display CAD currency properly. For example, with an event I created at $55.00 CAD, it displays in an event listing as 5,500.00 CAD AND UP. Is there a fix or workaround for this? 

Thanks!

**Comment by smccafferty** [comment]
This looks to be a bug in the parsing of the ticket prices returned from Eventbrite. As of now, I do not see a work around that can be used, keeping the currencies the same. We will have to get an update out for the theme.
